<#
.SYNOPSIS
    一鍵安裝 Claude 用量追蹤環境（Windows）。

.DESCRIPTION
    依序處理：
      1. 安裝 Claude Code CLI（官方安裝指令 irm https://claude.ai/install.ps1 | iex）
      2. 下載 claumon binary、加入 PATH
      3. 將 claumon 設為背景常駐（排程任務 watchdog：開機啟動＋每 3 分鐘自動重啟；每 2 分鐘記錄用量）
      4. 安裝本工具 claude-usage-tracker（pip install -e .）

    無法自動化的步驟：`claude` 登入為瀏覽器互動授權，需由使用者本人完成；
    腳本最後會提示。全程不需系統管理員權限。

.PARAMETER SkipClaudeCode
    略過 Claude Code CLI 安裝。

.PARAMETER SkipClaumon
    略過 claumon 下載與服務安裝。

.PARAMETER SkipTool
    略過本工具（pip install -e .）安裝。

.EXAMPLE
    powershell -ExecutionPolicy Bypass -File scripts\install.ps1
#>
[CmdletBinding()]
param(
    [switch]$SkipClaudeCode,
    [switch]$SkipClaumon,
    [switch]$SkipTool
)

$ErrorActionPreference = "Stop"

function Write-Step($n, $msg) { Write-Host "`n=== [$n] $msg ===" -ForegroundColor Cyan }
function Test-Cmd($name) { [bool](Get-Command $name -ErrorAction SilentlyContinue) }

$repoRoot = Split-Path -Parent $PSScriptRoot

# 1. Claude Code CLI ---------------------------------------------------------
if (-not $SkipClaudeCode) {
    Write-Step 1 "安裝 Claude Code CLI"
    if (Test-Cmd "claude") {
        Write-Host "已安裝，略過。"
    } else {
        # 官方 PowerShell 安裝指令；在其預期環境下執行（暫時放寬 ErrorAction，避免中途中止）
        Write-Host "執行官方安裝指令：irm https://claude.ai/install.ps1 | iex"
        $prevEAP = $ErrorActionPreference
        $ErrorActionPreference = "Continue"
        try {
            irm https://claude.ai/install.ps1 | iex
        } catch {
            Write-Warning "Claude Code 安裝失敗：$($_.Exception.Message)"
            Write-Warning "可稍後手動執行：irm https://claude.ai/install.ps1 | iex"
        } finally {
            $ErrorActionPreference = $prevEAP
        }
    }
} else { Write-Step 1 "略過 Claude Code CLI" }

# 2. claumon binary ----------------------------------------------------------
if (-not $SkipClaumon) {
    Write-Step 2 "下載 claumon binary"
    $dir = "$env:LOCALAPPDATA\Programs\claumon"
    $exe = "$dir\claumon.exe"
    New-Item -ItemType Directory -Force $dir | Out-Null
    # 重跑安裝時 watchdog 可能已把 claumon 拉起，先停掉以免 binary 被鎖無法覆寫
    Stop-Process -Name claumon -Force -ErrorAction SilentlyContinue
    $url = "https://github.com/fabioconcina/claumon/releases/latest/download/claumon-windows-amd64.exe"
    try {
        Invoke-WebRequest -Uri $url -OutFile $exe
        Unblock-File $exe
    } catch {
        if (Test-Path $exe) {
            Write-Warning "下載新版失敗（$($_.Exception.Message)），沿用現有 binary：$exe"
        } else { throw }
    }
    $p = [Environment]::GetEnvironmentVariable('Path', 'User')
    if ($p -notlike "*$dir*") {
        [Environment]::SetEnvironmentVariable('Path', "$p;$dir", 'User')
        Write-Host "已加入使用者 PATH：$dir"
    }
    Write-Host "claumon 安裝於 $exe"

    Write-Step 3 "設定 claumon 背景常駐（開機啟動 + 自動重啟）"
    # claumon 官方 service 只是把 claumon.vbs 放進 Startup：僅登入時啟動，被殺掉不會自己回來，
    # 且 `service status` 會把「已安裝」誤報成 running。改用排程任務 watchdog：
    #   - 登入即啟動、背景隱藏執行
    #   - 每 3 分鐘檢查，claumon 不在跑就自動拉回（防誤關）
    #   - 全程免系統管理員
    # 先移除官方 Startup(vbs)，避免與 watchdog 雙重啟動搶 3131 埠
    try { & $exe service uninstall | Out-Null } catch {}

    # 寫入 watchdog 腳本（純英文，避免編碼問題）：claumon 不在跑就隱藏重啟
    $watchdog = "$dir\claumon-watchdog.ps1"
    @'
# claumon watchdog - keep claumon alive. Generated by claude-usage-tracker install.ps1.
$exe = Join-Path $PSScriptRoot 'claumon.exe'
if (-not (Get-Process -Name claumon -ErrorAction SilentlyContinue)) {
    if (Test-Path $exe) { Start-Process -FilePath $exe -WindowStyle Hidden }
}
'@ | Set-Content -Path $watchdog -Encoding UTF8

    # 註冊/更新排程任務（idempotent；-Force 覆寫既有）
    $taskName = "ClaumonWatchdog"
    $me = "$env:USERDOMAIN\$env:USERNAME"
    $action = New-ScheduledTaskAction -Execute "powershell.exe" `
        -Argument "-NoProfile -NonInteractive -WindowStyle Hidden -ExecutionPolicy Bypass -File `"$watchdog`""
    $trigLogon = New-ScheduledTaskTrigger -AtLogOn -User $me
    $trigTick  = New-ScheduledTaskTrigger -Once -At (Get-Date) `
        -RepetitionInterval (New-TimeSpan -Minutes 3) -RepetitionDuration (New-TimeSpan -Days 3650)
    $settings = New-ScheduledTaskSettingsSet -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries `
        -StartWhenAvailable -MultipleInstances IgnoreNew -ExecutionTimeLimit (New-TimeSpan -Minutes 5)
    $principal = New-ScheduledTaskPrincipal -UserId $me -LogonType Interactive -RunLevel Limited
    try {
        Register-ScheduledTask -TaskName $taskName -Action $action -Trigger $trigLogon, $trigTick `
            -Settings $settings -Principal $principal `
            -Description "Keep claumon running: start at logon + auto-restart every 3 min (no admin)." -Force | Out-Null
        Write-Host "已建立背景常駐排程：$taskName（登入啟動 + 每 3 分鐘自動重啟）"
    } catch {
        Write-Warning "排程任務註冊失敗：$($_.Exception.Message)"
    }

    # 立即啟動一次，不必等到下次心跳/登入
    try { Start-ScheduledTask -TaskName $taskName } catch { Start-Process -FilePath $exe -WindowStyle Hidden }
} else { Write-Step 2 "略過 claumon" }

# 4. 本工具 ------------------------------------------------------------------
if (-not $SkipTool) {
    Write-Step 4 "安裝 claude-usage-tracker（pip install -e .）"
    if (Test-Cmd "python") {
        python -m pip install -e $repoRoot
    } else {
        Write-Warning "找不到 python；請先安裝 Python 3.9+ 後再執行：pip install -e ."
    }
} else { Write-Step 4 "略過本工具" }

# 完成提示 -------------------------------------------------------------------
Write-Host "`n----------------------------------------------------------" -ForegroundColor Green
Write-Host "安裝流程完成。還有一個手動步驟：" -ForegroundColor Green
Write-Host @"

  >> 登入 Claude（額度儀表才有資料，需瀏覽器授權）：

     claude

     首次啟動依指示完成登入後，claumon 最多 2 分鐘內會開始抓額度。
     要立即生效：Stop-Process -Name claumon -Force; Start-ScheduledTask ClaumonWatchdog

  背景常駐（已設定，免系統管理員）：
     claumon 由排程任務 ClaumonWatchdog 看守 —— 登入即啟動、背景隱藏，被關掉最多 3 分鐘自動拉回。
     確認運行：Get-Process claumon              # 或直接開 http://localhost:3131
     想停用：  Unregister-ScheduledTask -TaskName ClaumonWatchdog -Confirm:`$false

  之後查看與匯出：
     開啟 http://localhost:3131            # claumon dashboard
     claude-usage chart --days 7           # 一週用量曲線
     claude-usage export --month 2026-06   # 月度彙整 CSV

  注意：新開的終端機才會讓 claude / claumon / claude-usage 指令在 PATH 生效。
"@ -ForegroundColor Gray
